### ISSUE TITLE
mcad-controller-ray-clusterrolebinding refers to the wrong ServiceAccount

### ISSUE THREAD

**Issue by guimou** [opendatahub-io/codeflare-operator#21]
The RoleBinding defined at https://github.com/opendatahub-io/codeflare-operator/blob/main/config/rbac/mcad-controller-ray-clusterrolebinding.yaml refers to a ServiceAccount in the openshift-operators namespace:
```
subjects:
  - kind: ServiceAccount
    name: codeflare-operator-controller-manager
    namespace: openshift-operators
```
However this specific ServiceAccount is created in the namespace where the operator is deployed, so `opendatahub` or `redhat-ods-applications` normally. At least that's what is done using the Kustomize deployment.
So as the RB is pointing to the wrong SA, the Ray cluster cannot be created due to lack of permissions.
Maybe the operator takes care of the corrections automatically, but this is misleading when doing a manual install.
